# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'azuedevops-kube'
    namespace: 'default'
    manifests: 'apiVersion: v1 kind: Pod metadata:   name: nginx-pod-new   labels:     app: nginx spec:   containers:   - name: nginx     image: nginx:1.27.4     ports:     - containerPort: 80'