trigger:
- main

pool:
  name: default     # Your self-hosted agent pool name
  # you can optionally specify demands if needed:
  # demands:
  # - agent.name -equals fazil

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: KubernetesManifest@1
  inputs:
    action: 'delete'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'azuedevops-kube'
    namespace: 'default'
    arguments: '-f pod.yaml'
    
